### ISSUE TITLE
License related question

### ISSUE THREAD

**Issue by cclerget** [adigunhammedolalekan/registry-auth#1]
Hello @adigunhammedolalekan ,

We would like to use your package for another open source project (https://github.com/hpcng/singularity) as part of our e2e tests and as github licensing help mentioned:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

So we can't really use it either without your consent or with an appropriate license. Is it ok for you that we duplicate your code and set appropriate header and license attached to it ?

I also take the opportunity to mention an import issue with go modules because the module name in `go.mod` is `github.com/adigunhammedolalekan/docker-registry-auth` while github repo is `github.com/adigunhammedolalekan/registry-auth` leading to use a `replace` directive to import it without any error

**Comment by adxgun** [comment]
Hi, i have just added MIT license. Feel free to use it now.

Also, could you maybe make a PR that fixes the `go.mod` issue so that other future package users would not have this problem?

**Comment by cclerget** [comment]
Sure, thanks for the quick response :+1: !

**Comment by cclerget** [comment]
Closing the issue and submitted `go.mod` fix #2 . Thanks !
